### ISSUE TITLE
loggedInUser variable Unbound in endpoint_network_isolation_enforce.sh

### ISSUE THREAD

**Issue by nverselab** [jamf/jamfprotect#33]
Under the UserNotification event, the loggedInUser variable is not populated to execute IBM Notifier and fails to execute the notification.  Copying over the section from the Revert script and putting the variable in brackets resolves the issue.

`loggedInUser=$(/usr/sbin/scutil <<< "show State:/Users/ConsoleUser" | /usr/bin/awk '/Name :/ && ! /loginwindow/ { print $3 }')`

`/usr/bin/sudo -u ${loggedInUser} "$notificationApp" -type "$window" -bar_title "$barTitle" -title "$title" -subtitle "$subTitle" -always_on_top -main_button_label "$mainButtonLabel" -tertiary_button_label "$tertiaryButtonLabel" -tertiary_button_cta_type "$tertiaryButtonType" -tertiary_button_cta_payload "$tertiaryButtonPayload" -help_button_cta_type "$helpButtonType" -help_button_cta_payload "$helpButtonPayload" -icon_path "$iconPath" &`

**Comment by golbiga** [comment]
@nverselab #34 should resolve this issue. Not sure the ${loggedInUser} is needed.
