### ISSUE TITLE
Policy trigger or aftermath_collection.sh error

### ISSUE THREAD

**Issue by ronnieleblanc** [jamf/jamfprotect#53]
I noticed the policy trigger in the readme for [Google Cloud Aftermath Credentials](https://github.com/jamf/jamfprotect/tree/main/soar_playbooks/aftermath_collection/google_cloud_storage#policies) is currently `gcs_creds` but in the aftermath collection script it currently calls [/usr/local/bin/jamf policy -event gc_creds](https://github.com/jamf/jamfprotect/blob/52546f89e9077f9edc0a8333ec076b8c9268307b/soar_playbooks/aftermath_collection/google_cloud_storage/aftermath_collection.sh#L76) as the trigger.

**Comment by golbiga** [comment]
@ronnieleblanc, thanks for pointing this out. I updated the trigger in the script to match the readme.
