### ISSUE TITLE
Extension Attribute scripts not working correctly 

### ISSUE THREAD

**Issue by czernedo** [jamf/jamfprotect#66]
Hello, 

some of the extension attribute scripts are not working correctly with the latest Jamf Protect Version 4.0.0. 
Especially there are the following issues with the "jamf_protect_last_check_in_compliance.sh" script I was using.

The Output of the following command for example is empty because there are no colons after Status anymore and the column in the awk command does not match anymore.
```shell
jamf_protect_status=$(echo "$jamf_protect_info" | /usr/bin/grep 'Status:' | /usr/bin/awk '{print $2}')
``` 
It is working with the following though:
```shell
jamf_protect_status=$(echo "$jamf_protect_info" | /usr/bin/grep 'Status' | /usr/bin/awk '{print $4}')
``` 

There is a similar problem with the following command, where the columns $3 and $4 do not match anymore: 
```shell
jamf_protect_lastcheckin=$(echo "$jamf_protect_info" | /usr/bin/grep "Last Check-in" | /usr/bin/awk '{ print $3, $4 }' | /usr/bin/sed -e 's/ /-/g' -e 's/:/-/g' -e 's/\./-/g')
``` 
It's working with $5, $6: 
```shell
jamf_protect_lastcheckin=$(echo "$jamf_protect_info" | /usr/bin/grep "Last Check-in" | /usr/bin/awk '{ print $5, $6 }' | /usr/bin/sed -e 's/ /-/g' -e 's/:/-/g' -e 's/\./-/g')
``` 

Users might get empty Extensions Attributes as a result or parsing issues while running the script. 

Cheers,
Dominik

**Comment by golbiga** [comment]
@czernedo thanks for raising this issue. Can you check out the branch `task/issue_66`. I've made some changes so the EA should work properly. I removed the `grep` altogether and just using `awk`. Can you please test and let me know. Thanks again.

Allen

**Comment by jordanburnette** [comment]
Hey @golbiga, I am testing the change and so far it seems to be reporting back info on a number of machines that previously  were only returning a blank result. I will keep an eye on it through tomorrow to see if anything otherwise stands out. Appreciate your work on this!
